Lesson5
NankuF/geekshop pull request #5
Opened 2021-06-09 17:24 UTC by NankuF

Сделал все, кроме - 7*. Написать в модели корзины методы для определения общего количества и стоимости добавленных товаров. Вывести эти величины в шаблоне.

Нет идей, как это реализовать через ООП. Мало опыта.

Коммиты кривоваты (не отображают всего, что было сделано), тк еще хаос в голове.

2021-06-10 07:20 UTC, Vokler requested changes

2021-06-10 07:20 UTC, Vokler commented on users/views.py
> +        'title': 'GeekShop - Личный кабинет',
Попробуйте для начала добавить расчет total_quantity и total_sum сюда в контекст. То есть будет какое-то итоговое число вычислятся в контроллере, передаваться в контекст, а дальше в шаблоне уже вы обращаетесь к этим переменным

2021-06-11 06:34 UTC, NankuF commented on users/views.py
> +        'title': 'GeekShop - Личный кабинет',
rdy

2021-06-11 08:27 UTC, Vokler approved these changes

2021-06-11 08:27 UTC, merged